base_model: HuggingFaceTB/SmolLM2-1.7B
tokenizer_type: AutoTokenizer

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

strict: false


output_dir: ./outputs/model-out
max_steps: 200000
pretraining_dataset:
  - path: HuggingFaceFW/fineweb-2
    name: dan_Latn
    type: pretrain
    weight: 0.995  # Use 99.5% for training
  - path: HuggingFaceFW/fineweb-2
    name: dan_Latn
    type: eval
    weight: 0.005  # Use 0.5% for evaluation

dataset_prepared_path:
val_set_size: 0.0001
eval_strategy: steps
eval_steps: 0.1
output_dir: ./outputs/out

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project: smol-dan-1.7b
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 16
micro_batch_size: 32
num_epochs: 1
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true


warmup_steps: 100

eval_table_size:
saves_per_epoch: 2
eval_sample_packing: false

debug:
deepspeed:
weight_decay: 0.01

hub_model_id: syvai/smol-dan-1.7b
hub_strategy: checkpoint

fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_backward_prefetch: BACKWARD_PRE
  activation_checkpointing: true
special_tokens:
  pad_token: <|endoftext|>

# CodeCarbon configuration
codecarbon:
  project_name: "smol-dan-1.7b-training"
  output_dir: "./outputs/emissions"
  tracking_mode: "machine"
  log_level: "error"
  save_to_api: false
  save_to_file: true

